// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reloader

import (
	"context"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// After provides a mock function for the type MockClock
func (_mock *MockClock) After(d time.Duration) <-chan time.Time {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for After")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func(time.Duration) <-chan time.Time); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// MockClock_After_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'After'
type MockClock_After_Call struct {
	*mock.Call
}

// After is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockClock_Expecter) After(d interface{}) *MockClock_After_Call {
	return &MockClock_After_Call{Call: _e.mock.On("After", d)}
}

func (_c *MockClock_After_Call) Run(run func(d time.Duration)) *MockClock_After_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_After_Call) Return(timeCh <-chan time.Time) *MockClock_After_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *MockClock_After_Call) RunAndReturn(run func(d time.Duration) <-chan time.Time) *MockClock_After_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWatcher creates a new instance of MockWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatcher {
	mock := &MockWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatcher is an autogenerated mock type for the Watcher type
type MockWatcher struct {
	mock.Mock
}

type MockWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatcher) EXPECT() *MockWatcher_Expecter {
	return &MockWatcher_Expecter{mock: &_m.Mock}
}

// Watch provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Watch(ctx context.Context) (<-chan ChangeEvent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan ChangeEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan ChangeEvent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan ChangeEvent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ChangeEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatcher_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockWatcher_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWatcher_Expecter) Watch(ctx interface{}) *MockWatcher_Watch_Call {
	return &MockWatcher_Watch_Call{Call: _e.mock.On("Watch", ctx)}
}

func (_c *MockWatcher_Watch_Call) Run(run func(ctx context.Context)) *MockWatcher_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWatcher_Watch_Call) Return(changeEventCh <-chan ChangeEvent, err error) *MockWatcher_Watch_Call {
	_c.Call.Return(changeEventCh, err)
	return _c
}

func (_c *MockWatcher_Watch_Call) RunAndReturn(run func(ctx context.Context) (<-chan ChangeEvent, error)) *MockWatcher_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBuilder creates a new instance of MockBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuilder {
	mock := &MockBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBuilder is an autogenerated mock type for the Builder type
type MockBuilder struct {
	mock.Mock
}

type MockBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuilder) EXPECT() *MockBuilder_Expecter {
	return &MockBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockBuilder
func (_mock *MockBuilder) Build(ctx context.Context) (BuildResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 BuildResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (BuildResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) BuildResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(BuildResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBuilder_Expecter) Build(ctx interface{}) *MockBuilder_Build_Call {
	return &MockBuilder_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *MockBuilder_Build_Call) Run(run func(ctx context.Context)) *MockBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuilder_Build_Call) Return(buildResult BuildResult, err error) *MockBuilder_Build_Call {
	_c.Call.Return(buildResult, err)
	return _c
}

func (_c *MockBuilder_Build_Call) RunAndReturn(run func(ctx context.Context) (BuildResult, error)) *MockBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpstream creates a new instance of MockUpstream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpstream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpstream {
	mock := &MockUpstream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpstream is an autogenerated mock type for the Upstream type
type MockUpstream struct {
	mock.Mock
}

type MockUpstream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpstream) EXPECT() *MockUpstream_Expecter {
	return &MockUpstream_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockUpstream
func (_mock *MockUpstream) Start(ctx context.Context, artifact string) (ChildSession, error) {
	ret := _mock.Called(ctx, artifact)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 ChildSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ChildSession, error)); ok {
		return returnFunc(ctx, artifact)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ChildSession); ok {
		r0 = returnFunc(ctx, artifact)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ChildSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, artifact)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpstream_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockUpstream_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - artifact string
func (_e *MockUpstream_Expecter) Start(ctx interface{}, artifact interface{}) *MockUpstream_Start_Call {
	return &MockUpstream_Start_Call{Call: _e.mock.On("Start", ctx, artifact)}
}

func (_c *MockUpstream_Start_Call) Run(run func(ctx context.Context, artifact string)) *MockUpstream_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpstream_Start_Call) Return(childSession ChildSession, err error) *MockUpstream_Start_Call {
	_c.Call.Return(childSession, err)
	return _c
}

func (_c *MockUpstream_Start_Call) RunAndReturn(run func(ctx context.Context, artifact string) (ChildSession, error)) *MockUpstream_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChildSession creates a new instance of MockChildSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChildSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChildSession {
	mock := &MockChildSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChildSession is an autogenerated mock type for the ChildSession type
type MockChildSession struct {
	mock.Mock
}

type MockChildSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChildSession) EXPECT() *MockChildSession_Expecter {
	return &MockChildSession_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function for the type MockChildSession
func (_mock *MockChildSession) CallTool(ctx context.Context, params *mcp.CallToolParams) (*mcp.CallToolResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *mcp.CallToolResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mcp.CallToolParams) (*mcp.CallToolResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mcp.CallToolParams) *mcp.CallToolResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.CallToolResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *mcp.CallToolParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChildSession_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockChildSession_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - params *mcp.CallToolParams
func (_e *MockChildSession_Expecter) CallTool(ctx interface{}, params interface{}) *MockChildSession_CallTool_Call {
	return &MockChildSession_CallTool_Call{Call: _e.mock.On("CallTool", ctx, params)}
}

func (_c *MockChildSession_CallTool_Call) Run(run func(ctx context.Context, params *mcp.CallToolParams)) *MockChildSession_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *mcp.CallToolParams
		if args[1] != nil {
			arg1 = args[1].(*mcp.CallToolParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChildSession_CallTool_Call) Return(callToolResult *mcp.CallToolResult, err error) *MockChildSession_CallTool_Call {
	_c.Call.Return(callToolResult, err)
	return _c
}

func (_c *MockChildSession_CallTool_Call) RunAndReturn(run func(ctx context.Context, params *mcp.CallToolParams) (*mcp.CallToolResult, error)) *MockChildSession_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockChildSession
func (_mock *MockChildSession) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChildSession_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockChildSession_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockChildSession_Expecter) Close() *MockChildSession_Close_Call {
	return &MockChildSession_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockChildSession_Close_Call) Run(run func()) *MockChildSession_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChildSession_Close_Call) Return(err error) *MockChildSession_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChildSession_Close_Call) RunAndReturn(run func() error) *MockChildSession_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockChildSession
func (_mock *MockChildSession) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockChildSession_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockChildSession_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockChildSession_Expecter) Done() *MockChildSession_Done_Call {
	return &MockChildSession_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockChildSession_Done_Call) Run(run func()) *MockChildSession_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChildSession_Done_Call) Return(valCh <-chan struct{}) *MockChildSession_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockChildSession_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockChildSession_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Tools provides a mock function for the type MockChildSession
func (_mock *MockChildSession) Tools() []*mcp.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tools")
	}

	var r0 []*mcp.Tool
	if returnFunc, ok := ret.Get(0).(func() []*mcp.Tool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*mcp.Tool)
		}
	}
	return r0
}

// MockChildSession_Tools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tools'
type MockChildSession_Tools_Call struct {
	*mock.Call
}

// Tools is a helper method to define mock.On call
func (_e *MockChildSession_Expecter) Tools() *MockChildSession_Tools_Call {
	return &MockChildSession_Tools_Call{Call: _e.mock.On("Tools")}
}

func (_c *MockChildSession_Tools_Call) Run(run func()) *MockChildSession_Tools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChildSession_Tools_Call) Return(tools []*mcp.Tool) *MockChildSession_Tools_Call {
	_c.Call.Return(tools)
	return _c
}

func (_c *MockChildSession_Tools_Call) RunAndReturn(run func() []*mcp.Tool) *MockChildSession_Tools_Call {
	_c.Call.Return(run)
	return _c
}

// ToolsChanged provides a mock function for the type MockChildSession
func (_mock *MockChildSession) ToolsChanged() <-chan []*mcp.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToolsChanged")
	}

	var r0 <-chan []*mcp.Tool
	if returnFunc, ok := ret.Get(0).(func() <-chan []*mcp.Tool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []*mcp.Tool)
		}
	}
	return r0
}

// MockChildSession_ToolsChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToolsChanged'
type MockChildSession_ToolsChanged_Call struct {
	*mock.Call
}

// ToolsChanged is a helper method to define mock.On call
func (_e *MockChildSession_Expecter) ToolsChanged() *MockChildSession_ToolsChanged_Call {
	return &MockChildSession_ToolsChanged_Call{Call: _e.mock.On("ToolsChanged")}
}

func (_c *MockChildSession_ToolsChanged_Call) Run(run func()) *MockChildSession_ToolsChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChildSession_ToolsChanged_Call) Return(toolsCh <-chan []*mcp.Tool) *MockChildSession_ToolsChanged_Call {
	_c.Call.Return(toolsCh)
	return _c
}

func (_c *MockChildSession_ToolsChanged_Call) RunAndReturn(run func() <-chan []*mcp.Tool) *MockChildSession_ToolsChanged_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFrontend creates a new instance of MockFrontend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFrontend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFrontend {
	mock := &MockFrontend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFrontend is an autogenerated mock type for the Frontend type
type MockFrontend struct {
	mock.Mock
}

type MockFrontend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFrontend) EXPECT() *MockFrontend_Expecter {
	return &MockFrontend_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type MockFrontend
func (_mock *MockFrontend) Reconcile(tools []*mcp.Tool, call CallToolFunc) error {
	ret := _mock.Called(tools, call)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*mcp.Tool, CallToolFunc) error); ok {
		r0 = returnFunc(tools, call)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFrontend_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type MockFrontend_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - tools []*mcp.Tool
//   - call CallToolFunc
func (_e *MockFrontend_Expecter) Reconcile(tools interface{}, call interface{}) *MockFrontend_Reconcile_Call {
	return &MockFrontend_Reconcile_Call{Call: _e.mock.On("Reconcile", tools, call)}
}

func (_c *MockFrontend_Reconcile_Call) Run(run func(tools []*mcp.Tool, call CallToolFunc)) *MockFrontend_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*mcp.Tool
		if args[0] != nil {
			arg0 = args[0].([]*mcp.Tool)
		}
		var arg1 CallToolFunc
		if args[1] != nil {
			arg1 = args[1].(CallToolFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFrontend_Reconcile_Call) Return(err error) *MockFrontend_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFrontend_Reconcile_Call) RunAndReturn(run func(tools []*mcp.Tool, call CallToolFunc) error) *MockFrontend_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
